
name: ROS Noetic build.

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: autobuild
      run: |
        sh /home/murilo/autobuild/build.sh -e
