name: ROS2 Humble build

on:
  push:
    branches: [ ros2 ]

jobs:
  build:

    runs-on: ros2

    steps:
    - uses: actions/checkout@v2
    - name: autobuild
      run: /home/murilo/autobuild/build_ros2.sh
